---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: frontend
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: vijaymihiran/counterapp:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  namespace: frontend
spec:
  type: NodePort
  ports:
  - nodePort: 30001
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
      app: myapp

